-- Add new poster styles from H1 to J3
-- This migration adds 21 new style templates to the treasures table

-- H1-H7 styles
INSERT INTO treasures (title, description, prompt, main_image_url, additional_images, tags, category, is_featured) VALUES
(
  'H1: Dreamy Event',
  'Ethereal rave flyer meets fine art photography editorial with soft aura blur subjects',
  'Design language: ethereal rave flyer meets fine art photography editorial. Every slide should feel like a physical poster shot on film — slightly soft, emotionally warm, visually hypnotic. BACKGROUND SYSTEM: Soft lavender-violet field (#C9B8E8 family). Background is never flat — it breathes. Apply a subtle radial luminance shift: slightly brighter at center, darker at corners. Background should feel like a room lit by a single pink stage light. CENTRAL VISUAL LANGUAGE: One dominant subject per slide — human figure, body part, or organic form — rendered as a soft aura blur. Subject has NO hard edges. Think: heat haze, overexposed film, thermal imaging. Warm coral-to-orange gradient light radiates FROM INSIDE the form outward. Glow bleeds into background. The figure and background merge — you feel the subject more than see it. This is the emotional core of every slide. It must feel warm against cool. LIGHT + ATMOSPHERE: Internal light source. Subject glows from within. Background receives spill light — warm pink kissing the cool violet. No hard shadows anywhere. Depth comes from color temperature contrast: warm subject vs cool background. TYPOGRAPHY SYSTEM: Three distinct typographic zones, each a different scale and weight — together they create a 10:1:0.3 size hierarchy. TOP: ultra-thin small caps or fine sans-serif, maximum letter-spacing, near-invisible — functions as a decorative rule not readable text. MIDDLE: medium-weight name or category list spread horizontally full-width — equal rhythm, breathing spacing between items. BOTTOM: typographic explosion. Bold ultra-condensed grotesque at massive scale. Two-column architecture. Each word occupies its own visual territory. Between columns: small italic connector, almost apologetically small. Below: fine info strip — date, place, time — one line, featherweight type. COLOR PALETTE: lavender (#C9B8E8), coral-pink (#FF6B6B to #FF8C42 range), black (#111111), white (#FFFFFF). Warm glow lives in the coral-orange zone. Never add new hues. CONTENT DENSITY: top and middle zones sparse — air and space. Bottom zone: dense, loud, typographic. The contrast between emptiness above and typographic weight below IS the design. VARIATION ACROSS SLIDES: change the glowing subject each slide — figure, hands, face, abstract body. Change glow intensity and color temperature slightly. Bottom typography architecture stays consistent as the system anchor. Language: match user''s language.',
  '',
  '[]'::jsonb,
  ARRAY['creative', 'event', 'editorial', 'ethereal'],
  'creative',
  false
),
(
  'H2: Fluid Metallic',
  'Anarchist editorial poster meets Y2K digital underground with chrome 3D objects',
  'Design language: anarchist editorial poster meets Y2K digital underground. Aggressive. Printed matter energy — like a zine that somehow has a massive budget for one 3D render. CANVAS ARCHITECTURE: Hard horizontal split. Upper ~65% = electric lemon yellow (#F5E642). Lower ~35% = absolute black. The divide is a razor — hard, unforgiving, no transition. This split is structural law for every slide. It creates the tension. UPPER ZONE VISUAL: One large 3D rendered hero object, placed center-to-right. Object type: geometric sculptural forms — stars, spikes, blades, rings, crowns. Surface finish: chrome-metallic with cyan-blue iridescent quality. Think: liquid chrome meeting oil slick. Surface catches light from upper-left — sharp specular hotspot white, mid-tone cyan, shadow flank in deep navy. Object is physical, heavy, real. It casts a soft drop shadow onto the yellow field. In front of object: one flat silhouette figure, profile or dynamic pose, near-black, zero texture. Silhouette cuts across object — depth through flat-vs-dimensional contrast. LEFT TYPOGRAPHIC COLUMN: Bold condensed type running vertically, font enormous — each character or syllable fragment stacked. Type reads as visual texture. Starts in yellow zone, descends into black zone — color of type adapts: black in yellow, white in black. This column is graphic wallpaper. BLACK ZONE: Minimal. Barcode element one side. Copyright / year / brand mark other side. Bold, white, condensed. Year treated as massive graphic number. LIGHT LOGIC: single source upper-left. Chrome object catches it hard. Silhouette blocks light — feels like eclipse. COLOR RULES: yellow (#F5E642), black (#0A0A0A), cyan-iridescent chrome, white. These four carry everything. VARIATION: change the 3D hero object each slide. Change the silhouette pose. Keep the split, the column, the black zone locked. Language: match user''s language.',
  '',
  '[]'::jsonb,
  ARRAY['creative', 'editorial', '3d', 'metallic'],
  'creative',
  false
),
(
  'H3: Neo-Brutalist Holographic',
  'Product packaging meets web3 branding with holographic 3D objects on cream background',
  'Design language: product packaging meets web3 branding meets brutalist editorial. Feels like a cereal box designed by a hacker collective. Structured, industrial, oddly beautiful. BACKGROUND + CANVAS FEEL: Warm cream-beige (#F2EDE4). Not white. Aged paper quality — matte, slightly warm. The cream is the breathing space. Everything is placed in strict horizontal zones top to bottom like a product label grid. ZONE SYSTEM (describe atmosphere per zone): HEADER ZONE: sparse. Functional symbols — small circular icons, arrow marks, barcodes, registration symbols. Typographic size: tiny. These are utility graphics but styled with care. LOGOTYPE ZONE: the brand/title word is MASSIVE. Ultra-bold condensed black, full slide width, tight kerning. This word IS the visual. Trademark or registration symbol attached. Nothing competes with this. ACCENT STRIP: full-width pill or bar in solid orange (#F4631E). Inside: bold all-caps white subtitle. Left edge: pixel pattern or glitch texture in darker orange. This orange strip is the ONLY color on the page — it hits like an alarm. DETAIL ROW: tiny category labels, crosshair symbols, technical barcodes. All black on cream. Functions like metadata. FEATURE PANEL: large black rectangle, ~35% slide height. Inside this black field: one holographic 3D object, floating centered. Object surface: iridescent oil-slick rainbow — blue, green, yellow, purple, pink shifting across surface. Lit from above. Background black makes iridescence pop maximally. Shadow beneath object soft and diffused into black. FOOTER: left — small line-art illustration (globe, eye, symbol, icon) in black on cream. Right — small justified text paragraph, small serif font. Grounded, informational. SHADOW + LIGHT: only inside the black panel. Cream zones are flat, no shadow. COLOR RULES: cream, black, orange (#F4631E), iridescent spectrum (only on 3D object). VARIATION: swap holographic object each slide. Swap logotype zone content. Orange strip subtitle changes. Grid zones stay fixed. Language: match user''s language.',
  '',
  '[]'::jsonb,
  ARRAY['tech', 'brutalist', 'holographic', '3d'],
  'tech',
  false
),
(
  'H4: Industrial Techno',
  'Swiss International Style colliding with industrial rave culture and chrome sculptural forms',
  'Design language: Swiss International Style colliding with industrial rave culture. Discipline of Helvetica, aggression of a Berghain flyer. Type IS the design. BACKGROUND: electric vivid cobalt-blue (#1A12F5). Full saturation. Aggressive, not corporate. No texture, no gradient. The blue is a wall. TYPOGRAPHIC ARCHITECTURE (primary element): Two-word stacked headline. Each word = one line. Together they occupy top 50–55% of slide. Type: ultra-bold condensed grotesque, white. Font-size scaled so letters nearly touch left and right slide edges. Tracking: tight. Leading: tight — words nearly touch vertically. This is not decoration. This IS the slide. Treat letterforms as architectural forms. CENTRAL IMAGE COLLISION: Below the type — one high-contrast photograph or rendered object. B&W, fully desaturated, levels crushed to maximum contrast (blown highlights, deep blacks only). Subject: any physical object relevant to content — machine, body, tool, technology, structure. The object is ENTANGLED with chrome sculptural forms — metallic pipes, cables, tendrils, ribbons wrapping around it. Chrome surface: specular highlights white, mid chrome silver, shadow deep grey. Object sits center-to-left. Image collides with type base — overlaps by 10–15%. No clean separation. LIGHT: single directional source, upper-right. Chrome catches it hard — bright flare one side, deep shadow opposite. Creates sculptural volume. BOTTOM STRIP: minimal. Small white wordmark or label bottom-left, tiny address or caption fine type. Bottom-right: bold white condensed key number or date, large — treated as secondary typographic element, not afterthought. COLOR: blue (#1A12F5), white, black, chrome silver. No other hues. Chrome is achromatic. CONTENT: one concept per slide. The headline carries the message. Image supports viscerally. Never more than 8 words total per slide. VARIATION: swap the entangled object per slide. Chrome wrap style can change — cables vs pipes vs ribbons. Type wall stays. Language: match user''s language.',
  '',
  '[]'::jsonb,
  ARRAY['tech', 'industrial', 'rave', 'techno'],
  'tech',
  false
),
(
  'H5: Grindhouse',
  'Japanese exploitation cinema poster meets retro product catalog with suspended 3D objects',
  'Design language: Japanese exploitation cinema poster meets retro product catalog. Bold, tactile, slightly dangerous. Looks like it was printed in 1987 but feels completely contemporary. BACKGROUND: warm saturated yellow (#F5A800). The yellow of old Kodak boxes, caution tape, Japanese movie posters. Flat, matte. The yellow is loud and it should be. TOP SECTION VISUAL LOGIC: Left side: massive display title. Bold brush-gothic or heavy black type. Calligraphic weight even if latin. Font-size commanding — 25–30% slide height. Feels gestural and physical. Right side: small tight portrait panel. Thin black border framing it. Inside: high-contrast illustration or photo — face, character, subject. B&W or duo-tone. Manga ink quality: heavy shadows, white highlights cut sharp. Small label or initial beneath panel. Size contrast between title and portrait is the drama — massive vs tiny. BULLET LIST (mid-left area): 4–6 items. Fine black weight. Japanese dot bullets or simple dashes. Reads like a product spec sheet or film character stats. Informational, dry, contrasting with the emotional visuals. CENTER HERO OBJECT: One 3D rendered object, physically centered, dominant. Hanging from top edge via thick chain or suspended dramatically. Object: something with physical menace or beauty — weapon, tool, fruit, artifact, creature. Surface: glossy candy lacquer, deep red (#CC0000) or complementary saturated color. Specular highlight: sharp white hotspot. Shadow: hard dark ellipse beneath on yellow — feels heavy. Chain links: individually rendered, metallic dark red, specular edge highlight. Object must feel REAL and HEAVY in 2D space. BOTTOM: bold black condensed title/name, large. Behind it or beneath it: irregular ink-splat or torn shape in black. Fine weight date or descriptor below. COLORS: yellow (#F5A800), black (#111111), deep red (#CC0000). Three only. Object gloss lives in the red family. VARIATION: change hero object and its chain/suspension method per slide. Top portrait subject changes. Yellow-black-red system never changes. Language: match user''s language.',
  '',
  '[]'::jsonb,
  ARRAY['editorial', 'retro', 'cinema', 'grindhouse'],
  'editorial',
  false
),
(
  'H6: DIY Punk',
  'Photocopied punk gig poster with flat hot pink figures on near-black background',
  'Design language: photocopied punk gig poster, screen-printed on black paper stock. Handmade energy with graphic precision. Zero polish. Maximum impact. BACKGROUND: near-black (#0D0D0D). Warm dark, not cold. Feels like black paper absorbing ink. Apply faint grain or paper texture across entire slide at very low opacity — removes digital sterility, adds printed matter feel. ILLUSTRATION SYSTEM: One or multiple figures rendered in flat hot pink (#FF2D9A) — zero outlines, zero shadows, zero gradients. Pure flat fill only. Like ink pressed through a screen in one pass. Subject: skeletons, animals, figures, symbols, creatures — anything with strong silhouette energy. Poses: physically dynamic, contorted, expressive, impossible. Anatomy can be wrong — energy matters more than accuracy. Figures bleed off slide edges — never fully contained within frame. Overlapping figures stay same flat pink — depth through overlap, not shadow. The roughness IS the aesthetic — slightly imperfect edges like real screen-print registration. Hot pink on near-black vibrates optically — lean into this, maximize it. TYPOGRAPHY — LEFT COLUMN: Main title: ultra-bold condensed all-caps white, font-size massive, 2–3 words stacked, extremely tight leading. This text block commands the left side with authority. Supporting info below: bold condensed white, smaller — each item its own line, all-caps, medium-bold weight. Date, supporting names, location stack here. No thin weights. No decorative fonts. No mixing styles. Bold and bolder only. Small logo mark or stamp bottom-right, white. Typography slightly overlaps illustration — they share the same plane, no separation. SHADOW + LIGHT: none. Screen-print has no light logic. Everything is flat ink on paper. Depth = overlap only. COLOR: near-black (#0D0D0D), hot pink (#FF2D9A), white (#FFFFFF). Three colors. Any fourth color is a violation of the system. CONTENT VOLUME: never more than 6–7 text items per slide. Negative space (the dark field around illustration and type) is active — it creates the drama. VARIATION: change illustration subject and pose per slide. Title and info change per content. Flat pink technique, bleed rule, grain texture, three-color lock — these never change. Language: match user''s language.',
  '',
  '[]'::jsonb,
  ARRAY['punk', 'diy', 'editorial', 'handmade'],
  'editorial',
  false
),
(
  'H7: 3D Candy Mascot Magazine',
  'Y2K maximalist magazine cover with glossy kawaii CGI characters on electric cyan background',
  'Design language: Y2K maximalist magazine cover meets Japanese kawaii CGI toy catalog. Every slide should feel like a collectible issue pulled from a Tokyo convenience store in 2003 — loud, playful, saturated, oddly emotional. BACKGROUND SYSTEM: Electric cyan (#00D4D8 family) as the dominant canvas. Never flat — add a very subtle center-bright radial warmth so the field feels lit from behind. Background is the stage; everything performs on top of it. CENTRAL VISUAL LANGUAGE: One 3D CGI character or object per slide — rendered in glossy candy-plastic material. Think: oversized fruit with a face, a chubby tool with blush marks, an everyday object given anthropomorphic kawaii features. Surfaces are fully glossy, saturated, toy-store quality. Characters float centered with a soft drop shadow beneath. Each has a small cute face: dot eyes, round nose, blush marks. One character per slide, always the emotional anchor. TYPOGRAPHY SYSTEM: TOP: one massive chunky year-number or large display numeral spanning near full width — ultra-bold black with thick yellow outline. Graphic, not informational. RIGHT SIDE: vertical Japanese katakana column — bold black, reads downward, mid-scale. UPPER LEFT: small triangular or geometric logo badge — white text on dark triangle. UPPER RIGHT: bold parenthetical label "(CATEGORY)" — black condensed. BOTTOM LEFT: circular badge with small repeated text or number — yellow outline on cyan. BOTTOM RIGHT: small brand label + barcode strip — fine weight, functional graphic texture. COLOR PALETTE: electric cyan (#00D4D8), yellow (#F5E642), black (#111111), white (#FFFFFF), candy pink (#FF6EB4) used only on character details. Never add new hues beyond these five. CONTENT DENSITY: periphery loaded with typographic furniture — badges, labels, barcodes, vertical text. Center belongs entirely to the 3D character. The tension between packed edges and clean center IS the design. VARIATION ACROSS SLIDES: swap the 3D kawaii character per slide — one slide a fruit, next a household object, next an animal, next a tool. Change the large numeral to reflect content hierarchy. Keep cyan background, yellow numeral outline, katakana column, badge system consistent as the visual DNA across all slides. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['y2k', 'kawaii', 'magazine', 'playful'],
  'lifestyle',
  false
);

-- I1-I7 styles
INSERT INTO treasures (title, description, prompt, main_image_url, additional_images, tags, category, is_featured) VALUES
(
  'Punk Screen-Print Gig',
  'Photocopied punk gig poster with B&W halftone photography and hot pink graphic overlays',
  'Design language: photocopied punk gig poster colliding with screen-print zine culture. Every slide should feel physically printed — grain, texture, rough registration, handmade chaos with graphic intention. BACKGROUND SYSTEM: Near-black (#0D0D0D to #111111). Apply a faint paper grain texture at very low opacity across the entire canvas — removes digital sterility, adds printed-matter physicality. Background feels like black newsprint. CENTRAL VISUAL LANGUAGE: One high-contrast B&W photograph per slide — concert performer, athlete, or figure in powerful dynamic pose, singing or in motion. Image is grainy, screen-print quality: blown highlights, crushed blacks, halftone grain texture visible. Image occupies center-to-upper portion of slide. No color correction — raw and harsh. GRAPHIC OVERLAY SYSTEM: Bold hot pink (#FF2D9A) angular chevron arrows or geometric directional shapes flanking the central photo — left and right symmetrically. These are flat, zero-gradient, pure pink ink. Small pink sparkle star accents at corners. These graphics frame the photo without boxing it. TYPOGRAPHY SYSTEM: BOTTOM SECTION: large chunky hand-lettered style display type in hot pink — wobbly, playful, irregular letterforms. Text stacks 2–3 lines, fills bottom third. Feels like it was lettered with a fat marker, not typeset. Small star accents beside lettering. TOP: minimal — small label or event name, fine weight white or pink, near-invisible. COLOR: near-black (#0D0D0D), hot pink (#FF2D9A), white (#FFFFFF). Three colors only. B&W photo lives within this system — it IS the white and black. Any fourth color breaks the system. VARIATION ACROSS SLIDES: change the central B&W photograph per slide — different performer, subject, action. Change the bottom hand-lettered text to match slide content. Chevron arrows stay as the system anchor — they can shift in size but always flank the photo. Grain texture, three-color lock, wobbly type energy never changes. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['punk', 'gig', 'screen-print', 'editorial'],
  'editorial',
  false
),
(
  'Editorial Nature Poster',
  'Swiss International Style with duotone nature photography and bold red typography',
  'Design language: Swiss International Style grid meets contemporary duotone editorial photography. Every slide should feel like a high-end cultural institution poster — cream paper, bold red type, precise composition, one powerful image transformed by color. BACKGROUND SYSTEM: Cream off-white (#F5F0E8 family) — aged paper quality, matte, never clinical white. The cream breathes. It is the foundation everything is measured against. No texture, no gradient. Just warm, cultivated paper. CENTRAL VISUAL LANGUAGE: One photographic subject per slide — animal, plant, bird, natural object, human form. Rendered entirely in a single vivid electric duotone color: cobalt blue (#1A3FE0), acid green, or vivid orange — one color per subject, zero color mixing on the subject. The duotone is a graphic decision, not a filter. Subject fills mid-section of slide, clearly dominant. Edges may be slightly soft — photographic quality preserved within the color treatment. TYPOGRAPHY SYSTEM: BOTTOM: massive ultra-bold condensed sans-serif headline spanning full slide width — saturated red (#E8221A) or electric orange. Period included as intentional punctuation. This text is architectural — it anchors the slide. TOP RIGHT: small italic quote text — fine weight serif, one or two lines, upper right placement. TOP LEFT: small circular numbered badge — outline style, minimal. BACKGROUND LAYER: large semi-transparent year numeral or ghost number — bold condensed, very low opacity, bleeds into upper right area as texture. COLOR: cream (#F5F0E8), vivid single duotone for subject (blue/green/orange — one per slide), saturated red (#E8221A), black. Three active colors maximum per slide. VARIATION ACROSS SLIDES: swap subject and its duotone color per slide. Bottom headline text and italic quote change per content. Ghost numeral can remain consistent as a series marker. Cream background, red headline system, circular badge — these never change. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['editorial', 'nature', 'swiss', 'duotone'],
  'editorial',
  false
),
(
  '90S Athletic',
  '90s Nike vernacular with repeated blue typography wallpaper and B&W halftone athletes',
  'Design language: 90s Nike vernacular sports advertising — type as stadium, image as energy. Every slide should feel like a motivational poster that would be taped inside a locker room in 1994 — aggressive repetition, physical photography, no apology for loudness. BACKGROUND SYSTEM: Vivid saturated orange-red (#E8281A to #FF3300 family) — full bleed, wall-like. No gradient, no texture. The red IS the energy field. Everything else lives on top of it, competes with it. CENTRAL VISUAL LANGUAGE: One B&W halftone screen-print photograph of a person in motion — athlete running, jumping, performing, striding. High contrast, halftone grain visible, whites blown, blacks deep. Two figures can overlap — directional motion energy, left-to-right momentum. The photo cuts through the type field — figures exist inside the typographic wallpaper, not above it. TYPOGRAPHIC WALLPAPER SYSTEM: One short phrase — 3–5 words — repeated in massive ultra-bold condensed royal blue sans-serif, stacked row after row filling the ENTIRE slide. Each repetition spans full width. Rows slightly overlap. Text is the background, the atmosphere, the energy field. The photograph cuts through this wallpaper — creating depth through figure-versus-type collision. Slight text fragment variations between rows acceptable — emphasizes different words, creates reading rhythm. BOTTOM STRIP: small brand wordmark or logo bottom left. One supporting word or identifier bottom right. Both minimal. COLOR: orange-red (#E8281A), royal blue (#1A3AE0), black, white. Four colors — all carry equal weight. VARIATION ACROSS SLIDES: change repeated phrase to match slide content — one key message per slide. Change athlete figure per slide. Red field, blue type wallpaper, halftone B&W photo system stays constant. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['athletic', 'sports', '90s', 'motivational'],
  'specialized',
  false
),
(
  'Eye Blob Zine',
  'Handmade spray-art zine with organic blue blob containing repeated illustration elements',
  'Design language: handmade spray-art zine meets synaesthesia art event poster. Every slide should feel like it was stenciled and spray-painted by someone who sees sound — organic, slightly unhinged, completely intentional. BACKGROUND SYSTEM: Cream off-white (#F2EDE4) — aged paper texture, matte. Functions as the analog base. All graphic elements feel sprayed, painted, or stamped onto this surface. Never digital-clean. CENTRAL VISUAL LANGUAGE: One large irregular organic blob shape — electric royal blue (#1A2EF5), spray-painted with rough soft halo edges (not clean vector). The blob is the emotional core of every slide. Inside this blob: a repeated pattern of illustration elements — cartoon bold-line eyes (white eyeball, dark pupil), geometric grids of symbols, or a dense cluster of one recurring icon. The repetition of the element inside the blob creates visual intensity — grid of eyes, grid of mouths, grid of shapes. All inside the blue organic form. FLANKING GRAPHIC ELEMENTS: Left and right of the blob: simple icon graphics (speaker symbols, arrows, hands, symbols) — black outline, graphic weight, balanced symmetrically. These feel like rubber stamps. BOTTOM TYPOGRAPHY: Three column labels across the bottom — each in its own text column, bold condensed black caps. Small wavy tilde or wave pattern beneath each label — hand-drawn quality. TOP: one large bold condensed title spanning near full width — black, compressed, assertive. WAVE / RHYTHM ELEMENT: Below the blob: one or two bold wavy blue lines — spray quality, not vector-perfect. Adds rhythm and implies sound/motion. COLOR: cream (#F2EDE4), electric blue (#1A2EF5), black (#111111). Three colors only. Blob lives in blue. Everything else in black on cream. VARIATION ACROSS SLIDES: change the illustration element inside the blob — one slide eyes, next mouths, next hands, next abstract symbols. Change flanking icons. Three-column bottom labels change per content. Blob shape, color system, wavy lines stay fixed. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['zine', 'art', 'organic', 'handmade'],
  'creative',
  false
),
(
  'Modern Constructivism',
  'Japanese constructivist Bauhaus with geometric forms and B&W product photography',
  'Design language: Japanese constructivist Bauhaus poster meets mid-century product advertising. Every slide should feel like a museum artifact that also sells something — geometric abstraction as structural logic, product photography as the reality anchor. BACKGROUND SYSTEM: Cream off-white (#F2EDE4 to #EDE8DC) — aged, matte, paper-stock quality. Not white. The warmth of the cream makes the geometric primaries pop maximally. GEOMETRIC ARCHITECTURE SYSTEM: Two or three large geometric forms per slide — circle, rectangle, semicircle — in bold primary colors: red (#CC1A1A), black (#111111). Forms overlap and bisect each other to create abstract Bauhaus arrangements. No gradients, no shadows on geometric shapes. Geometry is flat and absolute. Forms occupy upper-left to center area of slide. CENTRAL PRODUCT ELEMENT: One high-contrast B&W product photograph — a glass, a bottle, a tool, an object — positioned atop the geometric arrangement. Dramatic studio lighting: sharp specular highlights, deep shadows, photographic realism. The B&W photograph anchors the abstract geometry in physical reality. Object sits where geometry converges. TYPOGRAPHY SYSTEM: TOP RIGHT: one large bold black kanji character or single symbol — large scale, architectural. Functions as cultural/conceptual label. LEFT SIDE: vertical katakana or foreign-script column — medium weight, reads downward. Category descriptor. BOTTOM RIGHT: small catalog identifier code — "D4-2" style, fine weight, minimal. COLOR: cream, red (#CC1A1A), black (#111111), B&W photography. No other hues. The photograph''s grays live within the black-and-white range. VARIATION ACROSS SLIDES: change geometric arrangement per slide — different overlap compositions. Change product photograph. Kanji/symbol top right changes per content. Cream, red, black system never changes. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['constructivism', 'bauhaus', 'product', 'geometric'],
  'creative',
  false
),
(
  'Risograph Circle Portrait',
  'Italian indie music poster with risograph orange duotone portrait grid on purple background',
  'Design language: Italian indie music gig poster meets risograph print culture. Every slide should feel physically printed in two passes — vivid background, orange duotone portraits, bold typography below. Intimate, warm, slightly imperfect. BACKGROUND SYSTEM: Vivid purple-violet (#9B20D4 to #B026E0) — full-bleed, punchy, no gradient. The purple is loud and warm. It IS the poster. PORTRAIT GRID SYSTEM: Upper two-thirds of slide: a grid of circles — 3×3 or 2×3 arrangement. Each circle contains a tightly cropped portrait photograph — face filling the circle, high-contrast orange duotone risograph treatment. Single orange color screen: all portraits are orange-on-dark, no color mixing. Circles are uniformly sized, evenly spaced, filling the grid zone. Portrait subjects vary — different people, angles, expressions. Grain and slight misregistration adds printed authenticity. TYPOGRAPHY SYSTEM: BOTTOM THIRD: one large ultra-bold black condensed grotesque name or title — massive scale, fills the width. This is the typographic event. Italic or upright — bold and absolute. BELOW TITLE: three small stacked info columns left, center, right — venue, date, access note. Fine weight, small scale. Each column sits in its own horizontal zone. CENTER BOTTOM: very small brand or label mark. COLOR: purple-violet (#9B20D4), orange duotone (#FF6A00 range on portraits), black (#111111). Three colors. Purple background, orange circles, black type. VARIATION ACROSS SLIDES: change portrait subjects per slide. Change title/name in bottom section per content. Grid layout (3×3 or 2×3) can flex. Purple background, orange risograph duotone treatment, bold black bottom type — these never change. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['risograph', 'music', 'portrait', 'editorial'],
  'editorial',
  false
),
(
  'Chrome Blob Typography',
  'Contemporary art gallery poster with photorealistic chrome blobs and bold black typography',
  'Design language: contemporary art gallery opening poster meets Swiss brutalist editorial. Every slide should feel like a high-end art object — ultra-minimal, physically luxurious, chrome and ink at war on white paper. BACKGROUND SYSTEM: Pure white (#FFFFFF) — clinical, uncompromising. No texture, no warmth. The white is a gallery wall. Everything on it must earn its place. 3D CHROME ELEMENT SYSTEM: Scattered across the full slide: multiple 3D photorealistic chrome liquid blob shapes — water droplets, morphing organic forms, spheres, fluid blobs at various scales. Surfaces are glass-like chrome: white specular highlights, mid-tone silver, soft reflections. No color — strictly monochromatic chrome. Blobs distributed freely, overlapping both text and each other. They float on the white field with soft shadows beneath. Size variety is essential — large blobs anchor, small beads scatter. TYPOGRAPHY SYSTEM: Large ultra-bold condensed black sans-serif text — fragments of sentences, titles, event details — placed across the slide in stacked lines. Text and chrome blobs SHARE THE SAME PLANE — they overlap freely, neither clearly above the other. Text is cropped at slide edges intentionally — words bleed off. No hierarchy between type and chrome. Both compete for dominance. This collision IS the design. Date, venue, and event details appear as secondary text at same or slightly smaller scale — same bold condensed style. COLOR: white (#FFFFFF), black (#111111), chrome silver (photorealistic, not flat). Absolutely no other colors. VARIATION ACROSS SLIDES: change blob quantity, size distribution, and arrangement per slide. Change text content per slide message. White-black-chrome system never changes. Type-bleeds-off-edge rule stays constant. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['gallery', 'art', 'chrome', 'brutalist'],
  'creative',
  false
);

-- J1-J3 styles
INSERT INTO treasures (title, description, prompt, main_image_url, additional_images, tags, category, is_featured) VALUES
(
  '3D Keycap Object',
  'Graphic design maximalism with 3D mechanical keyboard keycaps as alphabet letters',
  'Design language: graphic design maximalism meets keyboard internet culture — objects as alphabet, primary colors as visual language. Every slide should feel like an object exploded mid-flight and reassembled as a poster — physical, dimensional, slightly chaotic, completely readable. BACKGROUND SYSTEM: White-cream (#FAFAF5) — clean, neutral, high-contrast base. The background is deliberately quiet — it makes the dimensional objects pop. No texture. No gradient. 3D KEYCAP COMPOSITION SYSTEM: Multiple large 3D rendered mechanical keyboard keycaps scattered at varying angles across the slide filling the frame dynamically. Keycaps in primary colors — red, blue, green, yellow, warm gray. Each keycap displays one letter, number, or symbol in bold condensed sans-serif in a contrasting color. Together the keycap letters spell a word or phrase relevant to slide content. Keycaps are rendered with ABS plastic sheen — specular highlights, cast shadows, physical depth. They tilt at dynamic angles — never flat, never aligned. Diagonal energy, explosive scatter composition. TYPOGRAPHY ANNOTATION SYSTEM: Multiple distinct typographic zones: TOP LEFT: small flight/series identifier — "Flight N08" style label, fine weight. TOP CENTER: headline in bold condensed sans-serif — the slide''s main message, clean and assertive. RIGHT SIDE: vertical small tracking text — descriptive subtitle, fine weight, reads downward. LEFT EDGE: vertical classification column — very fine type, almost illegible, functions as texture. BOTTOM CENTER: bold label word followed by body-copy sentence in smaller weight — "POINT" style anchor with supporting text. BOTTOM RIGHT: series volume identifier — small, fine weight. COLOR: white-cream base, primary red/blue/green/yellow (on keycaps only), black (#111111) for all type. Four active hues plus black. VARIATION ACROSS SLIDES: change keycap letter arrangement to spell different key words per slide. Change colors of individual keycaps. Scatter composition shifts — same energy, different arrangement. Annotation system stays in same zones, content changes. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['3d', 'keyboard', 'maximalism', 'objects'],
  'creative',
  false
),
(
  'Pop Art Silhouette',
  'Gen-Z risograph zine with CMYK overprint silhouettes and misregistration effect',
  'Design language: Gen-Z risograph zine meets CMYK overprint pop art. Every slide should feel like it was printed on a machine slightly out of registration — deliberate misalignment, flat color planes, raw energy, lo-fi luxury. BACKGROUND SYSTEM: Bright saturated yellow (#F5E300) — full bleed, electric, aggressive. The yellow is pure signal. Everything is layered on top of it. Background has slight paper texture at very low opacity — feels like yellowed newspaper stock. CENTRAL VISUAL SYSTEM: One photographic portrait or figure — repeated 3–4 times in sequential horizontal overlap. Each repetition is a flat CMYK color silhouette — cyan (#00AEEF), magenta (#EC008C), black (#111111), yellow (blending into background). Colors are flat fills — no gradients, no details. Misregistration is intentional: each color plane slightly offset from the others, creating motion blur / trail illusion. Together the overlapping planes form one figure moving through color space. The human form is visible but abstracted through flat color layering. TYPOGRAPHY SYSTEM: TOP: one massive ultra-bold serif or display typeface headline — spanning full poster width, blue or dark color, slight ink-bleed softness at edges (misregistration quality). This word IS the slide visually. LEFT COLUMN: two or three small bold caps stacked phrases — short punchy copy, left-aligned, below headline. RIGHT COLUMN: small copyright or brand identifier — fine caps, right-aligned, same level as left column. CENTER: one short motivational or emotional line — small stacked bold caps, centered between left and right columns. COLOR: yellow (#F5E300), cyan (#00AEEF), magenta (#EC008C), black (#111111). Strictly CMYK four-color system. No other hues. VARIATION ACROSS SLIDES: change the portrait subject and the phrase it''s paired with per slide. Change headline word. CMYK color trail system — same four colors, applied to new figure. Yellow background, misregistration aesthetic, flat silhouette system never changes. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['pop-art', 'cmyk', 'risograph', 'gen-z'],
  'creative',
  false
),
(
  'Mixed-Case Bold Figure',
  'Bauhaus exhibition design with mixed-case typography and vivid lime green duotone figures',
  'Design language: Bauhaus centennial exhibition design meets contemporary duotone figure photography. Every slide should feel like it belongs in a German museum while also stopping you on the street — mixed-case type as disruption, vivid figure photography as life force. BACKGROUND SYSTEM: Soft blush pink (#F2C4B0 to #EAAD98 family) — warm, slightly dusty, cultured. Never hot or aggressive. The pink is civilized — it creates warmth against the black type and vivid green figures. TYPOGRAPHIC ARCHITECTURE SYSTEM: The typography IS the slide structure. One large word or phrase broken into 2–3 lines of ultra-bold condensed black grotesque — lowercase with intentional uppercase interruptions within words (e.g., "bAUhAUs" style). Each line occupies a full horizontal band. Type is maximum-weight — letterforms are architectural, nearly touching edges. The mixed-case disruption is the conceptual engine — it looks wrong and right simultaneously. TOP LEFT: small institution label or descriptor — fine weight, 2 lines, unobtrusive. TOP RIGHT: large bold abbreviation or initials — black, heavy. BOTTOM: italic serif exhibition details — fine weight, 2–3 lines of dates, venue, URL. Small and precise. CENTRAL FIGURE ELEMENT: One overlaid vivid lime green duotone (#7FD400 family) photographic figure — human body in expressive physical motion: dancing, leaping, contorting, reaching. Single green color treatment — no detail, just vivid flat green form. Figure is positioned center-to-right, overlapping with the type bands. Figure and type share the same plane — the body cuts through the letterforms. Multiple bodies can intertwine as one visual mass. COLOR: blush pink (#F2C4B0), vivid lime green (#7FD400), black (#111111). Three colors. Type is black. Figure is green. Background is pink. Never deviate. VARIATION ACROSS SLIDES: change the figure''s pose and movement per slide — different physical energy each time. Change the type content. Mixed-case disruption rule, three-color system, pink-green-black lock never changes. Language: match user''s language for all text content.',
  '',
  '[]'::jsonb,
  ARRAY['bauhaus', 'exhibition', 'typography', 'figure'],
  'creative',
  false
);

-- Verify the data was inserted
SELECT 
  title,
  category,
  is_featured
FROM treasures
WHERE title LIKE 'H%' OR title LIKE 'I%' OR title LIKE 'J%'
ORDER BY title;

SELECT COUNT(*) as total_new_styles FROM treasures WHERE title LIKE 'H%' OR title LIKE 'I%' OR title LIKE 'J%';
